- hosts: localhost
  become: true

  
  vars:
    gitlab_version: '11.4.0-ce.0.el7'
    gitlab_domain: "curl http://169.254.169.254/latest/meta-data/public-hostname"
    gitlab_external_url: "http://{{ gitlab_domain }}/"
    gitlab_edition: "gitlab-ce"

    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: update all packages 
    yum:
      name: '*'
      update_cache: yes
      state: latest 
  - name: Install epel release
    yum: 
      name: epel-release
      state: installed


  roles:
    - role: geerlingguy.gitlab 
    - role: geerlingguy.pip
    - role: geerlingguy.docker
